Added a dark theme to the style.css
nitnelave/lldap pull request #215
Opened 2022-07-03 20:12 UTC by JaidenW

2022-07-03 20:33 UTC, JaidenW commented
<footer class="text-center text-muted fixed-bottom bg-light"> Should remain the same, i didn't realize that it was fixed and overlaps some elements, the bg-light tag is required, & handled via CSS override :)

2022-07-05 19:47 UTC, nitnelave requested changes

2022-07-05 19:47 UTC, nitnelave commented on app/static/style.css
> +  color:#fff!;
I think we don't want pure white on pure black. If we take Material design's recommendations (not that it's gospel, but it's a good starting guideline) we'd have a background of #121212 for the very back, up to #242424 for the most accentuated background, and a text color of at most #dedede

2022-07-06 15:14 UTC, nitnelave commented
What would you think of something like https://vinorodrigues.github.io/bootstrap-dark/ ? Rather than creating/maintaining our own dark theme.

2022-07-13 07:45 UTC, JaidenW commented
That might be better, especially if you intend to add anything else to it in the future, that would likely also likely make it easier for you to style things on your own

2022-07-13 12:58 UTC, nitnelave commented
Closing in favor of https://github.com/nitnelave/lldap/issues/250

2022-07-13 12:58 UTC, closed without merging