Add UUID and creation date to the frontend
nitnelave/lldap pull request #260
Opened 2022-07-15 16:48 UTC by ivanizag

These changes implement #211.

- UUID is added to the details view of users and groups.
- creation date is added as a column to the list of groups and to the groups detail view.

To do this I have added read only fields to the group details view using the same format that the user detail view has.

2022-07-15 16:50 UTC, nitnelave commented
Could you post some screenshots of how the new pages look like?

2022-07-15 16:56 UTC, ivanizag commented
User detail:
![image](https://user-images.githubusercontent.com/1457799/179271169-1f1ec1b0-8c62-4e8b-836a-f2673f840298.png)

Group list:
![image](https://user-images.githubusercontent.com/1457799/179271343-374658ff-630d-4a81-85fb-daf6621d24e9.png)

Group detail:
![image](https://user-images.githubusercontent.com/1457799/179271520-fff8795d-ebd6-4b14-bea5-1fe9beaaa532.png)

2022-07-15 17:18 UTC, nitnelave approved these changes
Looks great, thanks!

2022-07-18 18:53 UTC, ivanizag commented
Sorry, I forgot to run cargo fmt.
The tests workflows have to be launched again, but I don't have permissions.

2022-07-19 09:06 UTC, nitnelave requested changes

2022-07-19 09:06 UTC, nitnelave commented on server/src/infra/graphql/query.rs
> +    fn uuid(&self) -> &str {
Can you extend the `get_user_by_id` test to get uuid as well?

2022-07-19 18:58 UTC, ivanizag commented on server/src/infra/graphql/query.rs
> +    fn creation_date(&self) -> chrono::DateTime<chrono::Utc> {
Added to the existing test `get_user_by_id`

2022-07-20 06:03 UTC, nitnelave approved these changes

2022-07-21 10:10 UTC, merged

2022-07-21 10:10 UTC, nitnelave commented
Thanks!