example_configs,nexus: Add example for Sonatype Nexus Repository Manager 3
nitnelave/lldap pull request #458
Opened 2023-02-21 23:46 UTC by carolosf

Added an example for Nexus.

2023-02-22 09:52 UTC, nitnelave requested changes
Thanks for the config!

Could you also add it to the main README?

2023-02-22 09:52 UTC, nitnelave commented on example_configs/nexus.md
> +* Username or DN: `uid=admin,ou=people,dc=example,dc=com`
Maybe suggest to use a readonly user?

2023-02-22 09:52 UTC, nitnelave commented on example_configs/nexus.md
> +* Password: Your bind user's password
Maybe "That user's password" so that people don't look for their "bind" user if they don't know what it is.

2023-02-22 09:52 UTC, nitnelave commented on example_configs/nexus.md
> +* User Filter:  Leave empty to allow all users to log in
Maybe suggest `(memberOf=uid=nexus_users,ou=groups,dc=example,dc=com)`?

2023-02-22 09:52 UTC, nitnelave commented on example_configs/nexus.md
> +* Group object class: `posixGroup`
`groupOfUniqueNames` is the more canonical one.

2023-02-22 09:52 UTC, nitnelave commented on example_configs/nexus.md
> +* Role Name: e.g. lldap_admin (role in ldap)
There's no "role" in LDAP. Maybe "group"?

2023-02-23 01:08 UTC, carolosf commented
Thanks for the feedback applied all your suggested changes. By the way great work!

2023-02-23 08:29 UTC, nitnelave approved these changes

2023-02-23 08:30 UTC, nitnelave commented
Thanks! I'll merge it now.

2023-02-23 08:33 UTC, merged